/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package crud;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Victor
 */
public class JFrameCitas extends javax.swing.JFrame {

    // creamos un elemento 
    DefaultTableModel dtm; 
    // este será el modelo para nuestra tabla de citas
    // este elemento permite administrar la tabla 
    
    
    /**
     * Creates new form JFrameCitas
     */
    public JFrameCitas() {
        initComponents();
        this.btnGuardar.setEnabled(false);
        this.btnLimpiar.setEnabled(false);
        this.btnMostrar.setEnabled(false);
        // inicializamos nuestro objeto para manipular los datos de las tablas
        dtm = (DefaultTableModel) this.tblTablaCitas.getModel();
        // indicamos que cargaremos el modelo de nuestra tabla de citas, extraemos el modelo
        // de la tabla le hacemos un casteo ya que no sabemos
        // cual es ese modelo de datos entonces lo transformamos a un defaulttablemodel
        // y lo guardamos en dtm.
    }
    
    private void habilitarBotones(){
        this.btnAgregar.setEnabled(true); 
        this.btnCrear.setEnabled(true);
        this.btnGuardar.setEnabled(true);
        this.btnLimpiar.setEnabled(true);
        this.btnMostrar.setEnabled(true);
    }

    private void crearArchivo() throws IOException{
        File archivo = new File("Archivo.txt");
        // si el archivo existe habilitamos los botones
        if(archivo.exists()){
            habilitarBotones();
        }else{
            JOptionPane.showMessageDialog(this, "El archivo no existe, se ha creado",
                    "Gestion Archivos", JOptionPane.INFORMATION_MESSAGE);
            archivo.createNewFile(); // creo el nuevo archivo
            habilitarBotones();
        }
    }
    
    private void guardarArchivo(){
        try {
            FileWriter salvarArchivo = new FileWriter("Archivo.txt");
            
            for (int i = 0; i < this.tblTablaCitas.getRowCount(); i++) {
                salvarArchivo.write(dtm.getValueAt(i, 0).toString() + "\n");
                salvarArchivo.write(dtm.getValueAt(i, 1).toString() + "\n");
                salvarArchivo.write(dtm.getValueAt(i, 2).toString() + "\n");
                salvarArchivo.write(dtm.getValueAt(i, 3).toString() + "\n");
                salvarArchivo.write(dtm.getValueAt(i, 4).toString() + "\n");
                System.out.println("Se ha guardado");
            }
            salvarArchivo.close();
            System.out.println("se ha cerrado");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error" + e);
        }
    }
    
    private void mostrarArchivo(){
        String id, nombre, medico, motivo, fecha;
        String path = "Archivo.txt";
        
        File arcLectura = new File(path);
        try {
            // cargamos toda la lectura de nuestro archivo
            Scanner lecturaArchivo = new Scanner(arcLectura); 
            
            while(lecturaArchivo.hasNextLine()){ // mientras que la lectura tenga lineas por leer
                // cargamos linea por linea en las variables que hemos declarado
                id = lecturaArchivo.nextLine();
                nombre = lecturaArchivo.nextLine();
                medico = lecturaArchivo.nextLine();
                motivo = lecturaArchivo.nextLine();
                fecha = lecturaArchivo.nextLine();
                
                dtm.addRow(new Object[] {id, nombre, medico, motivo, fecha}); // creo y a la vez cargo el arreglo con los datos
                // de toda la fila
            }
            
        } catch (FileNotFoundException e) {
        }
    }
    
    private void limpiarTabla(){
        int fila = this.tblTablaCitas.getRowCount();
        for (int i = fila - 1; i >= 0 ; i--) { // ciclo for al reves para limpiar la ultima fila
            dtm.removeRow(i);
        }
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHeader = new javax.swing.JPanel();
        lbTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTablaCitas = new javax.swing.JTable();
        btnCrear = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnMostrar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlHeader.setBackground(new java.awt.Color(204, 204, 255));
        pnlHeader.setToolTipText("");
        pnlHeader.setAutoscrolls(true);
        pnlHeader.setDoubleBuffered(false);

        lbTitulo.setFont(new java.awt.Font("Monospaced", 1, 36)); // NOI18N
        lbTitulo.setText("Citas");

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHeaderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbTitulo)
                .addGap(260, 260, 260))
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lbTitulo)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        tblTablaCitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Medico", "Motivo", "Fecha"
            }
        ));
        jScrollPane1.setViewportView(tblTablaCitas);

        btnCrear.setText("Crear");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnMostrar.setText("Mostrar");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCrear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMostrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(btnCrear)
                        .addGap(26, 26, 26)
                        .addComponent(btnAgregar)
                        .addGap(26, 26, 26)
                        .addComponent(btnGuardar)
                        .addGap(27, 27, 27)
                        .addComponent(btnMostrar)
                        .addGap(29, 29, 29)
                        .addComponent(btnLimpiar)))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        guardarArchivo();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        // creamos un espacio en nuestra tabla para agregar datos
        dtm.addRow(new Object[] {"","","","",""});
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        try {
            crearArchivo(); // lo agregamos dentro de un try catch ya que el metodo
            // puede arrojar una excepcion
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Error" + ex);
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        // TODO add your handling code here:
        mostrarArchivo();
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        limpiarTabla();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameCitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameCitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameCitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameCitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameCitas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JTable tblTablaCitas;
    // End of variables declaration//GEN-END:variables
}
